trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.4.0'
  inputs:
    versionSpec: 5.4.0

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '7dda4f99-91b6-4154-98b4-1af9eb97dbc7/c309ac36-2679-4d99-b022-302cbf901141'

- task: VSBuild@1
  displayName: 'Build Source'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Execute Unit Tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: 'DotNet Pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/TheCommons.Forge.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersion

- task: NuGetCommand@2
  displayName: 'NuGet Push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '7dda4f99-91b6-4154-98b4-1af9eb97dbc7/c309ac36-2679-4d99-b022-302cbf901141'
    allowPackageConflicts: true
